// import 'bootstrap/js/src/alert'  
// import 'bootstrap/js/src/button'  
// import 'bootstrap/js/src/carousel'  
import '../../../node_modules/bootstrap/js/src/collapse'
import '../../../node_modules/bootstrap/js/src/dropdown'
// import 'bootstrap/js/src/modal'  
// import 'bootstrap/js/src/popover'  
import '../../../node_modules/bootstrap/js/src/scrollspy'
// import 'bootstrap/js/src/tab'  
// import 'bootstrap/js/src/toast'  
// import 'bootstrap/js/src/tooltip