
name: Rspec
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      mysql:
        image: mysql:5.7
        ports:
          - 3306

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      
      - name: Install MySQL
        run: sudo apt install mysql-server libmysqlclient-dev

      - name: Run bundle install
        run: |
          gem install bundler
          bundle install
      - name: Run rspec
        run: rspec .    

  
